- lib/server.js
- tests/server.test.js
Given an error in the CLI, this PR changes the new channel redirect to use a 301 status so that its not seen as an error, and the CLI still works.
Closes #10
> Return 301 for channel redirect

- lib/server.js
- src/components/App.js
- src/components/ListItem.js
Little did I know some of the properties of payloads I was referencing were added on by Heroku, which of course means they aren't present anywhere else (hat-tip to @tcbyrd for noticing that). This PR makes use of the right headers, as well as sets a timestamp for each new payload. It also fixes the duplication check which now works because the event IDs are the same.
> Replace Heroku-specific props with real ones

- lib/keep-alive.js
- lib/server.js
https://devcenter.heroku.com/articles/request-timeout#long-polling-and-streaming-responses
It works!
```
curl -H 'Accept: text/event-stream'  https://smee.io/omg                                        
id: 0
event: ready
data: {}
id: 1
event: ping
data: {}
id: 2
event: ping
data: {}
id: 3
event: ping
data: {}
```
> Ping every 30 seconds to keep the connection alive

- src/components/App.js
@JasonEtco I was having some problems with payloads showing up after #24 was deployed, so I took a minute to look over the logic to check for duplicates and noticed it was backwards. To avoid duplicates, we need to only log when the `findIndex()` method returns `-1` (meaning, the payload's ID does not exist in the log yet). This is also the value that gets returned on an empty array. I deployed this to a test server and sent a few payloads and I think it's working as intended.
> Add logs only when they don't have an existing index (return value is -1)

- package.json
There seems to be a compatibility error between `standard` and `babel-eslint`, resulting in false-positives for "undefined" static variables on ES6 classes. It does not occur in `babel-eslint@^7` (we are currently on v8), so I've downgraded our installed version.
💥 https://github.com/babel/babel-eslint/issues/487 💥
> Downgrade babel-eslint

- client/bin/smee.js
- client/index.js
- client/test/index.test.js
- lib/server.js
- tests/server.test.js
`GET /new` was returning a relative redirect to the new channel name, but [EventSource](https://npm.im/eventsource) doesn't appear to be smart enough to inherit the original request path. This adds tests for the client to ensure it can properly follow the redirect from `/new`, and fixes the server to return an absolute redirect.
> Fix issue with client connecting on /new

- client/README.md
- client/package.json
I pinged the owner of `smee` again, but still haven't heard anything back. In the mean time, since this package can also be used as a client in a node app, calling it `smee-client` makes more sense than `smee-cli`.
This renames it and adds a README.
Closes #19
> Rename to smee-client

- client/package.json
- package.json
We changed the repo name from `probot/webhooks` to `probot/smee`. We forgot to change the `package.json`(s) 📦
> Use correct repo

- server/public/index.html
- server/tests/__snapshots__/server.test.js.snap
@hiimbex reported that the emoji in the footer wasn't rendering properly on their machine. In switching over to an SVG, there isn't [an octicon](https://octicons.github.com/) that is a drop-in replacement for the Robot emoji (besides Hubot but thats not the same thing). So, because we ❤️ Probot, I've used the heart octicon.
> Replace 🤖 with SVG ❤

- server/src/components/App.js
- server/src/components/EventIcon.js
- server/src/components/ListItem.js
- server/tests/App.test.js
- server/tests/EventIcon.test.js
- server/tests/ListItem.test.js
- server/tests/__snapshots__/App.test.js.snap
Adds functionality for pinned events. This is to ensure that some events don't get deleted, and always stay at the top of the UI. I've wanted this kind of functionality when building a Probot App that requires a specific payload, and I've seen important payloads get lost in a big list.
Here's how it looks (where `installation` is pinned):
And the button to make it happen:
Closes #53
> Pin events

- server/src/components/ListItem.js
An alignment bug was introduced in #55 where a long paragraph caused the buttons to wrap to a second line. Thanks to @tcbyrd for pointing it out 💪 🎯
> Fix button alignment

- server/src/components/Blank.js
Once you start a new channel, if you didn't read the installation instructions for the CLI, it's too late :( So I added installation instructions from the new channel landing page.
> Add installation instuctions for CLI and Node.js usage.

- client/package.json
This PR sets the stage to release version 1.0.2. We don't have any big changes so this should be fairly straightforward:
* This PR updates our packages and bumps the `package.json` version.
* It also updates some outdated links.
Once this is merged I'll draft a release and publish to NPM.
cc @hiimbex - turns out that URL validation is in fact not published (yet!)
> Release v1.0.2

- server/src/components/ListItem.js
Acting on some feedback from @gautam & @johnkpaul, this PR changes the output of the `Copy` button to conform to what `robot.receive()` actually receives. Previously, the entire request was copied (headers, body); now, only the event and payload are copied. Specifically this:
```js
{
event: item['x-github-event'],
payload: item.body
}
```
> Change copy output to work as a fixture

- server/package.json
- server/server.js
- server/tests/server.test.js
This gets us part of the way towards #64 by sending errors to Sentry. Thinking we'll put it in the same Organization as the other Probot apps we host internally ([test issue](https://sentry.io/probot/smeeio/issues/604239965/))
> Add raven to send errors to sentry

- server/public/index.html
- server/public/webhooks.html
- server/tests/__snapshots__/server.test.js.snap
Update page titles to be more descriptive.
Often when needing to use [Smee.io](Smee.io) I'll type "webhook", unfortunately the main page title is not descriptive enough to show the site as a result.
See: https://support.google.com/webmasters/answer/35624 for general guidelines on page titles.
> Add descriptive page titles

- server/tests/server.test.js
Jest's default [test environment](https://jestjs.io/docs/en/configuration.html#testenvironment-string) is jsdom, and when running the tests on master, the following warning is logged in `server.test.js`:
```
❯ npm test
> smee-server@0.0.3 test /Users/macklinu/dev/probot/smee/server
> jest --coverage && eslint '**/*.js'
PASS  tests/server.test.js
● Console
console.warn node_modules/raven/lib/utils.js:147
raven@2.6.4 alert: This looks like a browser environment; are you sure you don't want Raven.js for browser JavaScript? https://sentry.io/for/javascript
PASS  tests/App.test.js
PASS  tests/ListItem.test.js
PASS  tests/Blank.test.js
PASS  tests/EventIcon.test.js
PASS  tests/EventDescription.test.js
Test Suites: 6 passed, 6 total
Tests:       38 passed, 38 total
Snapshots:   8 passed, 8 total …
```
> Fix console warning in server.js test

- client/bin/smee.js
I'd like to use smee in a docker-compose service to redirect GitHub events to a Rails instance which is running in another service.
I tried to use smee for that by installing it globally and calling it with the right arguments but I realized that it's not possible to pass the target through arguments. It defaults to `127.0.0.1:port/path`.
I've added support for a new argument, target. When passed, that target is used to initialize the client.
> Add support for target argument

- client/index.js
- client/test/index.test.js
- server/server.js
> add support for query string forwarding

- client/bin/smee.js
- client/package.json
Pulls in the version number from `package.json` and is returned when running `smee` with the `-v` or `--version` option.
Fixes #95
> Add version option to client CLI

- .gitignore
- .npmignore
- index.ts
- package-lock.json
- package.json
- test/index.test.ts
- tsconfig.json
> Typescript migration

- test/index.test.ts
This is a small fix for a codeql warning in the tests. We can merge this without a release, as we are not shipping tests with our npm packages.
> chore: resolve codeql warning in unit test

- index.ts
This PR aims to fix the issue with the forwarded payload not being in the correct JSON format.
```json
"1716450473706": {
"{"name":"Dasun Tharanga","email":"hello@dasun.dev"}":""
}
```
```json
"1716450473706": {
"name": "Dasun Tharanga",
"email": "hello@dasun.dev"
}
> fix: Incorrect JSON formatting in forwarded payload

- README.md
- index.ts
This PR adds proxy support for the `EventSource` which was missing.
Fixes #194
> fix: add proxy support for `EventSource`

- index.ts
- package-lock.json
- package.json
Unfortunately it isn't suitable as it completely swallows errors with no way of getting them.
No errors are thrown, and no details are included in the `error` event.
> fix: don't use undici EventSource

- index.ts
We should also export SmeeClient as named export.
> feat: add SmeeClient named export
