probot/smee-client

- package.json
- src/components/ListItem.js
> Add copy-to-clipboard button

- src/components/App.js
This updates the event source code to attempt to reconnect if there is an error and the client isn't already attempting to reconnect.
> Reconnect closed connection

- .gitignore
- .vscode/settings.json
- README.md
- docs/deploy.md
Now that we have a better vision of how this thing will work, I'd like to update the metadata surrounding it. This includes the README, the repo description, etc etc. I'm going to leave this open until we decide on a name, and may also include a screenshot of the webhooks view (when its ready).
> Improve repo metadata

- client/bin/smee.js
> Use smee.io as the default URL

- .babelrc
- package.json
- src/components/App.js
- src/components/EventDescription.js
- src/components/ListItem.js
- tests/EventDescription.test.js
- tests/ListItem.test.js
- tests/setup.js
- webpack.config.js
Add some tests, fix some things. Are these kinds of tests _really_ necessary? No, but I had a fun time playing with Enzyme. It did help me catch a couple of bugs that have been fixed here. Coverage is pretty good, couldn't test some browser-things (like fetch, copy-to-clipboard). Hoping to add EventSource tests soon though, but in a followup PR.
> Enzyme tests

- server/server.js
Very minor nit here, but this just removes the url unfriendly characters instead of replacing them with other characters. This has been bothering me for weeks.
Ok, I'm going to bed now and won't have to worry about waking up in a cold sweat about these urls any more.
> Remove all url unfriendly characters

- server/public/index.html
- server/tests/__snapshots__/server.test.js.snap
Notices we had a couple links here that were out of date.
> Update homepage links

- server/src/components/Blank.js
> fix CLI usage on website homepage

- server/src/components/App.js
Adds a <kbd>Clear logs</kbd> button to clear `localStorage` for that channel and update the App's state accordingly. Can be helpful when using the same channel across multiple apps and it gets cumbersome.
Closes #42 
---
So you can work on your GitHub Apps, _smee and clear_.
> Add Clear logs button

- server/public/webhooks.html
- server/tests/__snapshots__/server.test.js.snap
Looks like some code copied over from TODO. I was looking at this for a completely unrelated reason, but figured I'd change it while I'm here.
> Update no-script links

- client/index.js
- client/package.json
- client/test/__snapshots__/index.test.js.snap
- client/test/index.test.js
> Validated URL, and reported correct error

- .travis.yml
- server/package.json
- server/tests/App.test.js
- server/tests/Blank.test.js
This upgrade `smee-server` to run in Node@10, and removes the Node@8 test environment from TravisCI. I've gone ahead and verified that everything works as expected locally 🎉
> Upgrade to Node 10

- server/package.json
I'd like to help fix the build issue in #86 and am opening this PR to get things building in CI to help debug in that environment since @JasonEtco and I were seeing different successes/errors locally (see https://github.com/probot/smee/pull/86#issuecomment-447961638).
> Help resolve build issue in #86

- server/src/components/App.js
- server/src/components/ListItem.js
- server/tests/App.test.js
@JasonEtco here's a proposal for implementing a fix for #76.
> Allow for duplicate requests when no x-github-delivery header is specified

- client/package.json
> Update deps for the client package

- package-lock.json
- package.json
Merging several dependabot PRs into one:
https://github.com/probot/smee-client/pull/177
https://github.com/probot/smee-client/pull/175
https://github.com/probot/smee-client/pull/174
https://github.com/probot/smee-client/pull/171
https://github.com/probot/smee-client/pull/167
https://github.com/probot/smee-client/pull/166
> Depedency updates

- index.ts
- package-lock.json
- package.json
Closes https://github.com/probot/smee-client/issues/192
Tests are passing and I verified locally against one of my development GitHub Apps. Everything seems to work 👍
> Bump packages that have deprecations

- package-lock.json
- package.json
resolves https://github.com/probot/smee-client/pull/260#issuecomment-1817168633
> build(deps): ping `@types/eventsource` to 1.1.8

- index.ts
> fix: delete the `Host` eader

- .github/workflows/ci.yml
- README.md
- index.ts
- package-lock.json
- package.json
- test/index.test.ts
- tsconfig.json
BREAKING CHANGE: This package has now migrated to ESM only
> chore!: esm only

- package-lock.json
- package.json
- test/index.test.ts
using the simple HttpServer from node is enough for testing
> chore: remove fastify
